version: '3.9'
services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=testuser
      - DB_PASSWORD=password
      - DB_NAME=testdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql